/*
	Name: Taliban_fighters
	Author: Yettie
	Date: 25/04/17
	Description: CfgUnits.hpp
*/


class O_Soldier_base_F;
	
	class TBan_Fighter1: O_Soldier_base_F
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Leader";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=70;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		magazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F"};
		respawnMagazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_01";
		modelSides[]={3};
		uniformClass="U_Afghan01";
	};
	class TBan_Fighter1NH: O_Soldier_base_F
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Leader (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=70;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		magazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F"};
		respawnMagazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_01NH";
		modelSides[]={3};
		uniformClass="U_Afghan01NH";
	};
	class TBan_Fighter2: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter kar98k";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_kar98k",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_kar98k",
			"Throw",
			"Put"
		};
		magazines[]={"rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k"};
		respawnMagazines[]={"rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_02";
		modelSides[]={3};
		uniformClass="U_Afghan02";
	};
	class TBan_Fighter2NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter kar98k (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_kar98k",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_kar98k",
			"Throw",
			"Put"
		};
		magazines[]={"rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k"};
		respawnMagazines[]={"rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k","rhsgref_5Rnd_792x57_kar98k"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_02NH";
		modelSides[]={3};
		uniformClass="U_Afghan02";
	};
	class TBan_Fighter3: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter AKM";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		Backpack="rhs_rpg_empty";
		weapons[]=
		{
			"arifle_AKM_F",
			"launch_RPG7_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKM_F",
			"launch_RPG7_F",
			"Throw",
			"Put"
		};
		magazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","RPG7_F","RPG7_F"};
		respawnMagazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","RPG7_F","RPG7_F"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};
	class TBan_Fighter3NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter AKM (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		Backpack="rhs_rpg_empty";
		weapons[]=
		{
			"arifle_AKM_F",
			"launch_RPG7_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKM_F",
			"launch_RPG7_F",
			"Throw",
			"Put"
		};
		magazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","RPG7_F","RPG7_F"};
		respawnMagazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","RPG7_F","RPG7_F"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_03NH";
		modelSides[]={3};
		uniformClass="U_Afghan03NH";
	};
	class TBan_Fighter4: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter4";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter pkp";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_pkp",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_pkp",
			"Throw",
			"Put"
		};
		magazines[]={"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};
		respawnMagazines[]={"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_04";
		modelSides[]={3};
		uniformClass="U_Afghan04";
	};
	class TBan_Fighter5: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter5";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter pkm";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_pkm",
			"Throw",
			"Put"
		};
		magazines[]={"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};
		respawnMagazines[]={"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_05";
		modelSides[]={3};
		uniformClass="U_Afghan05";
	};
	class TBan_Fighter6: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter6";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter m76";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_m76",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_m76",
			"Throw",
			"Put"
		};
		magazines[]={"rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76"};
		respawnMagazines[]={"rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_06";
		modelSides[]={3};
		uniformClass="U_Afghan06";
	};
	class TBan_Fighter6NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter6";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter m76 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"rhs_weap_m76",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_m76",
			"Throw",
			"Put"
		};
		magazines[]={"rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76"};
		respawnMagazines[]={"rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76","rhsgref_10Rnd_792x57_m76"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_06NH";
		modelSides[]={3};
		uniformClass="U_Afghan06NH";
	};
	class TBan_Warlord: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		backpack = "B_Kitbag_cbr";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban AA";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=80;
		weapons[]=
		{
			"arifle_AKM_F",
			"rhs_weap_fim92",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKM_F",
			"rhs_weap_fim92",
			"Throw",
			"Put"
		};
		magazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","rhs_fim92_mag","rhs_fim92_mag"};
		respawnMagazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","rhs_fim92_mag","rhs_fim92_mag"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};

	class Haji_Matin: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"Nikos",
			"NoGlasses"
		};
		displayName="Haji Matin (HVT)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=80;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		magazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F"};
		respawnMagazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};

	class Afghan_civilian1: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian1";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Village Leader";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=70;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F"};
		respawnMagazines[]={"30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F","30Rnd_762x39_Mag_Green_F"};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_01";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan01";
	};
	class Afghan_civilian1NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian1";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Village Leader (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=70;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"",
			"Throw",
			"Put"
		};
		magazines[]={""};
		respawnMagazines[]={""};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_01NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan01NH";
	};
	class Afghan_Civilian2: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian2";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 1";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_02";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan02";
	};
	class Afghan_Civilian2NH: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian2";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 1 (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_02NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan02NH";
	};
	class Afghan_civilian3: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian3";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 2";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan03";
	};
	class Afghan_civilian3NH: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian3";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 2 (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_03NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan03NH";
	};
	class Afghan_Civilian4: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian4";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 3";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_04";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan04";
	};
	class Afghan_Civilian5: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian5";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 4";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_05";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan05";
	};
	class Afghan_Civilian6: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian6";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 5";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_06";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan06";
	};
	class Afghan_Civilian6NH: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian6";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 5 (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_06NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan06NH";
	};


